<?php

$UUID = $_SESSION['WPSDrelease']['WPSD']['UUID'];

if (!file_exists('/etc/wpsd-css.ini')) {
    $outFile = fopen("/tmp/bW1kd4jg6b3N0DQo.tmp", "w") or die("Unable to open file!");
    $headers = stream_context_create(Array("http" => Array("method"  => "GET",
                                                           "timeout" => 10,
                                                           "header"  => "User-agent: WPSD-CSS-Default - v.$versionCmd - $callsign - $UUID",
                                                           'request_fulluri' => True )));
    $fileContent = @file_get_contents("https://wpsd-swd.w0chp.net/WPSD-SWD/WPSD-Helpers/raw/branch/master/supporting-files/WPSD-CSS.ini", false, $headers);
    fwrite($outFile, $fileContent);
    fclose($outFile);
                    
    exec('sudo cp /tmp/bW1kd4jg6b3N0DQo.tmp /etc/wpsd-css.ini');  // Move the file back
    exec('sudo chmod 644 /etc/wpsd-css.ini');                     // Set the correct runtime permissions
    exec('sudo chown root:root /etc/wpsd-css.ini');               // Set the owner
}

// Do not edit this file, instead use the appearance tool in the Admin section

// Output CSS and not plain text
header("Content-type: text/css");

// Default values
$backgroundPage = "#212529";			// main page bkgnd color
$backgroundContent = "#212529";			// The background color in the content section
$backgroundBanners = "#2e363f";			// banner bkgnd. color
$backgroundNavbar = "#2e363f";			// Navbar background color
$backgroundNavbarHover = "##65737e";		// Navbar hover color
$backgroundDropdown = "#6b6c73";		// Dropdown menu background color
$backgroundDropdownHover = "#3c3f47";		// Dropdown hover background color
$backgroundNavPanel = "#242d31";		// Background color of left side nav panel
$backgroundServiceCellActiveColor = "#11DD11";
$backgroundServiceCellInactiveColor = "#8C0C26";
$backgroundModeCellDisabledColor = "#606060";
$backgroundModeCellActiveColor = "#00BB00";
$backgroundModeCellInactiveColor = "#8C0C26";
$backgroundModeCellPausedColor = "#ff9933";
$tableRowEvenBg = "#949494";			// Table Row BG Color (Even)
$tableRowOddBg = "#7a7c80";			// Table Row BG Color (Odd)

$textBanners = "#bebebe";			// Header color
$textNavbar = "#bebebe";			// Navbar text color
$textNavbarHover = "#ffffff";			// Navbar hover color
$textDropdown = "#fffff";			// Dropdown menu text color
$textDropdownHover = "#ffffff";			// Dropdown hover menu text color
$textTableHeaderColor = "#bebebe";		// table header text color
$textServiceCellActiveColor = "#ffffff";
$textServiceCellInactiveColor = "#bebebe";
$textModeCellDisabledColor = "#b3b3af";
$textModeCellActiveColor = "#ffffff";
$textModeCellInactiveColor = "#bebebe";

$textContent = "#000000";			// Used for most content
$textSections = "#bebebe";			// Used for the section titles
$textLinks = "#1a2573";

// extras
$mainFontSize = "18";				// Default font size used across most of the dashboard
$bodyFontSize = "17";				// Default font size used across rest of the dashboard
$headerFontSize = "34";				// Default font size used for main header
$lastHeardRows = "40";
$tableBorderColor = "#3c3f47";

// Assign $value to $var only when it's set, otherwise use default value.
// That avoids messing when wpsd-css.ini has changed.
function assignCSSValue(&$var, $value) {
    if (isset($value)) {
	$var = $value;
    }
}

// Check if the config file exists
if (file_exists('/etc/wpsd-css.ini')) {
    // Use the values from the file
    $piStarCssFile = '/etc/wpsd-css.ini';
    if (fopen($piStarCssFile,'r')) {
	$piStarCss = parse_ini_file($piStarCssFile, true);
    }
    
    // Set the Values from the config file
    assignCSSValue($backgroundPage, $piStarCss['Background']['PageColor']);
    assignCSSValue($backgroundContent, $piStarCss['Background']['ContentColor']);
    assignCSSValue($backgroundBanners, $piStarCss['Background']['BannersColor']);
    assignCSSValue($backgroundNavbar, $piStarCss['Background']['NavbarColor']);
    assignCSSValue($backgroundNavbarHover, $piStarCss['Background']['NavbarHoverColor']);
    assignCSSValue($backgroundDropdown, $piStarCss['Background']['DropdownColor']);
    assignCSSValue($backgroundDropdownHover, $piStarCss['Background']['DropdownHoverColor']);
    assignCSSValue($backgroundNavPanel, $piStarCss['Background']['NavPanelColor']);

    assignCSSValue($backgroundServiceCellActiveColor, $piStarCss['Background']['ServiceCellActiveColor']);
    assignCSSValue($backgroundServiceCellInactiveColor, $piStarCss['Background']['ServiceCellInactiveColor']);
    assignCSSValue($backgroundModeCellDisabledColor, $piStarCss['Background']['ModeCellDisabledColor']);
    assignCSSValue($backgroundModeCellActiveColor, $piStarCss['Background']['ModeCellActiveColor']);
    assignCSSValue($backgroundModeCellInactiveColor, $piStarCss['Background']['ModeCellInactiveColor']);
    assignCSSValue($backgroundModeCellPausedColor, $piStarCss['Background']['ModeCellPausedColor']);
    
    assignCSSValue($tableRowEvenBg, $piStarCss['Background']['TableRowBgEvenColor']);
    assignCSSValue($tableRowOddBg, $piStarCss['Background']['TableRowBgOddColor']);

    assignCSSValue($textContent, $piStarCss['Text']['TextColor']);
    assignCSSValue($textSections, $piStarCss['Text']['TextSectionColor']);
    assignCSSValue($textLinks, $piStarCss['Text']['TextLinkColor']);
    assignCSSValue($textTableHeaderColor, $piStarCss['Text']['TableHeaderColor']);
    assignCSSValue($textBanners, $piStarCss['Text']['BannersColor']);
    assignCSSValue($textNavbar, $piStarCss['Text']['NavbarColor']);
    assignCSSValue($textNavbarHover, $piStarCss['Text']['NavbarHoverColor']);
    assignCSSValue($textDropdown, $piStarCss['Text']['DropdownColor']);
    assignCSSValue($textDropdownHover, $piStarCss['Text']['DropdownHoverColor']);
    assignCSSValue($textServiceCellActiveColor, $piStarCss['Text']['ServiceCellActiveColor']);
    assignCSSValue($textServiceCellInactiveColor, $piStarCss['Text']['ServiceCellInactiveColor']);
    assignCSSValue($textModeCellDisabledColor, $piStarCss['Text']['ModeCellDisabledColor']);
    assignCSSValue($textModeCellActiveColor, $piStarCss['Text']['ModeCellActiveColor']);
    assignCSSValue($textModeCellInactiveColor, $piStarCss['Text']['ModeCellInactiveColor']);
    
    assignCSSValue($lastHeardRows, $piStarCss['ExtraSettings']['LastHeardRows']);
    assignCSSValue($mainFontSize, $piStarCss['ExtraSettings']['MainFontSize']);
    assignCSSValue($bodyFontSize, $piStarCss['ExtraSettings']['BodyFontSize']);
    assignCSSValue($headerFontSize, $piStarCss['ExtraSettings']['HeaderFontSize']);
    assignCSSValue($tableBorderColor, $piStarCss['ExtraSettings']['TableBorderColor']);
    
}